### ISSUE TITLE
Add support for multiple secrets

### ISSUE THREAD

**Issue by alxxyz** [Azure/k8s-create-secret#81]
At the moment we should call the action multiple times in case we have multiple secrets.
It will be useful to set multiple secrets at once in one action call.

**Comment by OliverMKing** [comment]
Hi @alxxyz! We don't want to add this feature because it would significantly complicate the way users have to use this action (actions can't take lists or other yaml features as inputs). Running the action multiple times should be just as effective of a solution.

Is there a reason why you want this action to be able to set multiple secrets at the same time instead of just running this action multiple times?

**Comment by alxxyz** [comment]
Hi @OliverMKing, we have to pass 20-30 secrets, and it looks bad when we need to pass such amount of secrets

**Comment by Cluster2a** [comment]
> Hi @alxxyz! We don't want to add this feature because it would significantly complicate the way users have to use this action (actions can't take lists or other yaml features as inputs). Running the action multiple times should be just as effective of a solution.
> 
> Is there a reason why you want this action to be able to set multiple secrets at the same time instead of just running this action multiple times?

In most of our applications we need multiple secrets (besides the docker pull secret) - so adding a resource for each secret seems not the best option.

**Comment by mihiic** [comment]
@alxxyz 
Would this work for you?
Store whole secret manifest inside a github secret, and then apply it as a resource directly?

For example:
```
apiVersion: v1
kind: Secret
metadata:
  name: <secret name>
  namespace: <namespace name>
type: Opaque
data:
  DB_PASSWORD: <b64 of database password>
  RMQ_PASSWORD: <b64 of rmq password>
  JWT_SECRET_KEY: <b64 of jwt secret>
```

And then in your workflow definition:

```
steps:
  - name: Set secret
    run: |
      echo {{ secrets.APP_SECRET_MANIFEST }} | kubectl apply -f -
    shell: bash
```
