### ISSUE TITLE
kubelogin ENOENT

### ISSUE THREAD

**Issue by alxxyz** [Azure/k8s-create-secret#88]
```
    name: Set secret
    uses: azure/k8s-create-secret@v4
    with:
      namespace: ${{ inputs.namespace }}
      secret-type: 'generic'
      secret-name: database-data
      string-data: '{"data": "Very secret data"}'
```

I get an error for this action
```
Run azure/k8s-create-secret@v4
Warning: Failed to delete secret with statusCode: undefined
Deleting secret:
undefined
Creating secret
***"errno":-2,"code":"ENOENT","syscall":"spawnSync kubelogin","path":"kubelogin","spawnargs":["get-token","--environment","AzurePublicCloud"

How to fix this?
```

**Comment by davidgamero** [comment]
@alxxyz can you attach the rest of the workflow? which action are you using to set your context before calling k8s-create-secret?

**Comment by alxxyz** [comment]
Hi @davidgamero, these are other actions
```
  - name: Authenticate to AKS
    uses: azure/login@v1
    with:
      creds: ${{ inputs.principal }}
      
  - name: Set AKS Context
    uses: azure/aks-set-context@v3
    with:
        cluster-name: ${{ inputs.cluster-name }}
        resource-group: ${{ inputs.resource-group }}
        subscription: ${{ inputs.subscription }}
```

**Comment by davidgamero** [comment]
are you using this as a non-admin user? you may need to add [kubelogin](https://github.com/Azure/aks-set-context#kubelogin)

You can do this by adding `use-kubelogin: 'true'` to your aks-set-context "with" clause and adding this step before it:
```
- name: Set up kubelogin for non-interactive login
  uses: azure/use-kubelogin@v1
  with:
     kubelogin-version: 'v0.0.24'
```
